-- 1. 
SELECT student_no 학번, student_name 이름, to_char(entrance_date, 'YYYY-MM-DD') 입학년도 FROM tb_student WHERE department_no = 02 ORDER BY TB_STUDENT.ENTRANCE_DATE;	

-- 2.
SELECT professor_name, professor_ssn FROM TB_PROFESSOR tp WHERE professor_name NOT LIKE '___';

-- 3.
SELECT professor_name 교수이름, 125 - to_number(substr(professor_ssn,1,2)) 나이 FROM tb_professor ORDER BY 2;
SELECT professor_name 교수이름, FLOOR(MONTHS_BETWEEN(sysdate,TO_DATE(substr(professor_ssn,1,6),'YYMMDD')-365*100)/12) 나이 FROM tb_professor ORDER BY 2;
SELECT professor_name 교수이름, TO_DATE(substr(professor_ssn,1,6),'YYMMDD')-365*100 FROM tb_professor ORDER BY 2;

-- 4.
SELECT substr(professor_name,2) 이름 FROM tb_professor;

-- 5. 
SELECT ts.STUDENT_NAME FROM TB_STUDENT ts WHERE EXTRACT(YEAR FROM TO_DATE(SUBSTR(STUDENT_SSN,1,6),'RRMMDD'))+19 < EXTRACT(YEAR FROM ts.ENTRANCE_DATE);

-- 6.
SELECT TO_CHAR(TO_DATE('2020-12-25'),'DAY') "2020년 크리스마스" FROM DUAL;

-- 7.
SELECT TO_DATE('99/10/11','YY/MM/DD') FROM DUAL; -- 2099
SELECT TO_DATE('49/10/11','YY/MM/DD') FROM DUAL; -- 2049
SELECT TO_DATE('99/10/11','RR/MM/DD') FROM DUAL; -- 1999
SELECT TO_DATE('49/10/11','RR/MM/DD') FROM DUAL; -- 2049
SELECT TO_DATE('50/10/11','RR/MM/DD') FROM DUAL; -- 1950
SELECT TO_DATE('51/10/11','RR/MM/DD') FROM DUAL; -- 1951
SELECT TO_DATE('00/10/11','RR/MM/DD') FROM DUAL; -- 2000

-- 8.
SELECT STUDENT_NO, STUDENT_NAME FROM TB_STUDENT WHERE STUDENT_NO NOT LIKE 'A%';

-- 9.
SELECT ROUND(AVG(TG.POINT),1) 평점 FROM TB_GRADE tg WHERE STUDENT_NO = 'A517178';

-- 10.
SELECT DEPARTMENT_NO 학과번호, COUNT(*) 학생수 FROM TB_STUDENT GROUP BY DEPARTMENT_NO ORDER BY 학과번호;

-- 11.
SELECT COUNT(*) FROM TB_STUDENT WHERE COACH_PROFESSOR_NO IS NULL;

-- 12.
SELECT SUBSTR(TERM_NO,1,4) 년도, ROUND(AVG(POINT),1) "년도 별 평균 학점" FROM TB_GRADE tg WHERE STUDENT_NO = 'A112113' GROUP BY SUBSTR(TERM_NO,1,4) ORDER BY 년도;

-- 13.
SELECT ts.DEPARTMENT_NO 학과코드, COUNT(*) 휴학생 FROM TB_STUDENT ts WHERE ts.ABSENCE_YN = 'Y' GROUP BY DEPARTMENT_NO ORDER BY 학과코드;
SELECT TD.DEPARTMENT_NO 학과코드, COUNT(TS.STUDENT_NO) 휴학생 FROM TB_DEPARTMENT td LEFT JOIN TB_STUDENT ts ON(TD.DEPARTMENT_NO = TS.DEPARTMENT_NO ) AND TS.ABSENCE_YN ='Y' GROUP BY TD.DEPARTMENT_NO ORDER BY 학과코드;
SELECT department_no 학과코드, count(CASE WHEN absence_yn = 'Y' THEN 1 end) 휴학생 FROM tb_student GROUP BY department_no ORDER BY department_no;

-- 14.
SELECT DISTINCT STUDENT_NAME 이름, COUNT(*) 인원 FROM TB_STUDENT ts GROUP BY ts.STUDENT_NAME HAVING COUNT(*)>1;

-- 15. 
SELECT SUBSTR(TERM_NO,1,4) 년도, SUBSTR(TERM_NO,5,2)학기, ROUND(AVG(POINT), 1) 평점 FROM TB_GRADE tg WHERE STUDENT_NO = 'A112113' GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,5,2)) ORDER BY 년도;