-- 1. 
SELECT TS.STUDENT_NAME  "학생 이름", TS.STUDENT_ADDRESS 주소지
FROM TB_STUDENT ts 
ORDER BY "학생 이름";

-- 2.
SELECT TS.STUDENT_NAME 이름, TS.STUDENT_SSN 주민번호
FROM TB_STUDENT ts 
WHERE ts.ABSENCE_YN = 'Y'
ORDER BY 주민번호 DESC;

-- 3.
SELECT TS.STUDENT_NAME 학생이름, TS.STUDENT_NO 학번, TS.STUDENT_ADDRESS 주소지, TS.ENTRANCE_DATE
FROM TB_STUDENT ts 
WHERE (TS.STUDENT_ADDRESS LIKE '강원도%'
OR TS.STUDENT_ADDRESS LIKE '경기도%')
AND TS.ENTRANCE_DATE<'2000-01-01';

-- 4.
SELECT * FROM TB_DEPARTMENT td ;
SELECT TP.PROFESSOR_NAME 이름, TP.PROFESSOR_SSN 주민번호
FROM TB_PROFESSOR tp
WHERE TP.DEPARTMENT_NO = '005'
ORDER BY TP.PROFESSOR_SSN;

-- 5.
SELECT * FROM TB_STUDENT ts ;
SELECT * FROM TB_GRADE tg ;
SELECT TG.STUDENT_NO 학번, TG.POINT 학점
FROM TB_GRADE tg
WHERE TG.TERM_NO = '200402'
AND TG.CLASS_NO = 'C3118100'
ORDER BY 학점 DESC, 학번;

-- 6.
SELECT TS.STUDENT_NO 학번, TS.STUDENT_NAME 이름, TD.DEPARTMENT_NAME 학과
FROM TB_STUDENT ts, TB_DEPARTMENT td
WHERE TS.DEPARTMENT_NO =TD.DEPARTMENT_NO
ORDER BY 이름;

-- 7.
SELECT*FROM TB_CLASS tc ;
SELECT*FROM TB_DEPARTMENT td ;
SELECT TC.CLASS_NAME 강의명, TD.DEPARTMENT_NAME 학과
FROM TB_CLASS tc 
JOIN TB_DEPARTMENT td USING (DEPARTMENT_NO);

-- 8.
SELECT * FROM TB_PROFESSOR tp ;
SELECT * FROM TB_CLASS_PROFESSOR tcp ;
SELECT TC.CLASS_NAME 강의명, TP.PROFESSOR_NAME 교수
FROM TB_CLASS tc, TB_CLASS_PROFESSOR tcp, TB_PROFESSOR tp
WHERE TC.CLASS_NO  = TCP.CLASS_NO
AND TCP.PROFESSOR_NO = TP.PROFESSOR_NO;

-- 9.
SELECT * FROM tb_class;
SELECT * FROM TB_DEPARTMENT;
SELECT TC.CLASS_NAME 강의명, TP.PROFESSOR_NAME 교수
FROM TB_CLASS tc, TB_CLASS_PROFESSOR tcp, TB_PROFESSOR tp, TB_DEPARTMENT td 
WHERE TC.CLASS_NO  = TCP.CLASS_NO
AND TCP.PROFESSOR_NO = TP.PROFESSOR_NO
AND tc.DEPARTMENT_NO = td.DEPARTMENT_NO 
AND td.CATEGORY = '인문사회';

-- 10.
SELECT student_no, student_name, round(avg(point),1)
FROM TB_STUDENT
JOIN TB_GRADE using(STUDENT_NO)
where TB_STUDENT.DEPARTMENT_NO = (SELECT department_no FROM TB_DEPARTMENT td WHERE td.DEPARTMENT_NAME ='음악학과')
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY student_no;

-- 11.
SELECT department_name 학과명, student_name "학생 이름", professor_name "교수 이름"
FROM TB_DEPARTMENT td, TB_STUDENT ts, TB_PROFESSOR tp
WHERE td.DEPARTMENT_NO = ts.DEPARTMENT_NO
AND ts.COACH_PROFESSOR_NO = tp.PROFESSOR_NO
AND ts.STUDENT_NO = 'A313047';

-- 12.
SELECT ts.STUDENT_NAME, tg.TERM_NO
FROM TB_STUDENT ts, TB_GRADE tg
WHERE ts.STUDENT_NO = tg.STUDENT_NO
AND term_no LIKE '2007%'
AND tg.CLASS_NO = (SELECT class_no FROM TB_CLASS tc WHERE class_name = '인간관계론');

-- 13.
SELECT class_name, department_name
FROM tb_class
JOIN TB_DEPARTMENT USING(department_no)
WHERE category = '예체능'
AND TB_CLASS.CLASS_NO NOT in (SELECT class_no FROM TB_CLASS_PROFESSOR tcp);

-- 14.
-- 15.
-- 16.
-- 17.
-- 18.
-- 19.