-- 1. 
SELECT TS.STUDENT_NAME  "학생 이름", TS.STUDENT_ADDRESS 주소지
FROM TB_STUDENT ts 
ORDER BY "학생 이름";

-- 2.
SELECT TS.STUDENT_NAME 이름, TS.STUDENT_SSN 주민번호
FROM TB_STUDENT ts 
WHERE ts.ABSENCE_YN = 'Y'
ORDER BY 주민번호 DESC;

-- 3.
SELECT TS.STUDENT_NAME 학생이름, TS.STUDENT_NO 학번, TS.STUDENT_ADDRESS 주소지, TS.ENTRANCE_DATE
FROM TB_STUDENT ts 
WHERE (TS.STUDENT_ADDRESS LIKE '강원도%'
OR TS.STUDENT_ADDRESS LIKE '경기도%')
AND TS.ENTRANCE_DATE<'2000-01-01';

-- 4.
SELECT * FROM TB_DEPARTMENT td ;
SELECT TP.PROFESSOR_NAME 이름, TP.PROFESSOR_SSN 주민번호
FROM TB_PROFESSOR tp
WHERE TP.DEPARTMENT_NO = '005'
ORDER BY TP.PROFESSOR_SSN;

-- 5.
SELECT * FROM TB_STUDENT ts ;
SELECT * FROM TB_GRADE tg ;
SELECT TG.STUDENT_NO 학번, TG.POINT 학점
FROM TB_GRADE tg
WHERE TG.TERM_NO = '200402'
AND TG.CLASS_NO = 'C3118100'
ORDER BY 학점 DESC, 학번;

-- 6.
SELECT TS.STUDENT_NO 학번, TS.STUDENT_NAME 이름, TD.DEPARTMENT_NAME 학과
FROM TB_STUDENT ts, TB_DEPARTMENT td
WHERE TS.DEPARTMENT_NO =TD.DEPARTMENT_NO
ORDER BY 이름;

-- 7.
SELECT*FROM TB_CLASS tc ;
SELECT*FROM TB_DEPARTMENT td ;
SELECT TC.CLASS_NAME 강의명, TD.DEPARTMENT_NAME 학과
FROM TB_CLASS tc 
JOIN TB_DEPARTMENT td USING (DEPARTMENT_NO);

-- 8.
SELECT * FROM TB_PROFESSOR tp ;
SELECT * FROM TB_CLASS_PROFESSOR tcp ;
SELECT TC.CLASS_NAME 강의명, TP.PROFESSOR_NAME 교수
FROM TB_CLASS tc, TB_CLASS_PROFESSOR tcp, TB_PROFESSOR tp
WHERE TC.CLASS_NO  = TCP.CLASS_NO
AND TCP.PROFESSOR_NO = TP.PROFESSOR_NO;

-- 9.
-- 10.
-- 11.
-- 12.
-- 13.
-- 14.
-- 15.
-- 16.
-- 17.
-- 18.
-- 19.