CREATE TABLE tb_member (
    MEMBER_NO NUMBER CONSTRAINT member_no_pk PRIMARY KEY,
    ID VARCHAR2(30) CONSTRAINT id_nn NOT NULL CONSTRAINT id_unq UNIQUE,
    PW VARCHAR2(30) CONSTRAINT pw_nn NOT NULL,
    NAME VARCHAR2(30) CONSTRAINT name_nn NOT NULL,
    SSN VARCHAR2(50) CONSTRAINT snn_nn NOT NULL
);

COMMENT ON COLUMN tb_member.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN tb_member.ID IS '아이디';
COMMENT ON COLUMN tb_member.PW IS '비밀번호';
COMMENT ON COLUMN tb_member.NAME IS '이름';
COMMENT ON COLUMN tb_member.SSN IS '주민등록번호';

CREATE TABLE tb_todo (
    TODO_NO NUMBER CONSTRAINT todo_no_pk PRIMARY KEY,
    TITLE VARCHAR2(50) CONSTRAINT title_nn NOT NULL,
    TODO_YN VARCHAR2(1) DEFAULT 'N' CONSTRAINT todo_yn_ck CHECK (TODO_YN IN ('Y','N')),
    CREATE_DATE DATE DEFAULT CURRENT_DATE,
    CONTENT VARCHAR2(1000),
    MEMBER_NO NUMBER CONSTRAINT member_no_fk REFERENCES tb_member(MEMBER_NO) ON DELETE CASCADE
);

COMMENT ON COLUMN tb_todo.TODO_NO IS '할일 번호';
COMMENT ON COLUMN tb_todo.TITLE IS '제목';
COMMENT ON COLUMN tb_todo.TODO_YN IS '할일 여부 (Y: 완료, N: 미완료)';
COMMENT ON COLUMN tb_todo.CREATE_DATE IS '생성 날짜';
COMMENT ON COLUMN tb_todo.CONTENT IS '내용';
COMMENT ON COLUMN tb_todo.MEMBER_NO IS '회원 번호 (tb_member 참조)';

CREATE SEQUENCE MEMBER_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE TODO_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE
NOCYCLE
NOCACHE;

SELECT * FROM tb_member;
SELECT * FROM tb_todo;

INSERT INTO tb_member
VALUES(member_seq.nextval, 'user01', 'pass01', 'name', 'ssn');
INSERT INTO tb_todo
VALUES(todo_seq.nextval, 'title01', 'N', sysdate, 'content01', 'member_no');